// src/utils/midnightClient.js
import { WalletBuilder } from "@midnight-ntwrk/wallet";
import { getZswapNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import {
  CompactRuntime,
  InMemorySigner,
  ZswapNodeSyncProvider,
  defaultProofServiceConfiguration,
} from "@midnight-ntwrk/compact-runtime";

// Your compiled contract (generated by `compact compile`)
import { AseryxModule } from "../../../contracts/managed/aseryx/contract/index.cjs";
import deployment from "../../../deployment.json" with { type: "json" };

// === Load seed from Vite env ===
const seedHex = import.meta.env.VITE_WALLET_SEED?.trim();
if (!seedHex || !/^[0-9a-fA-F]{64}$/.test(seedHex)) {
  throw new Error("VITE_WALLET_SEED is missing or invalid in your frontend .env");
}

// === Build wallet exactly like your backend does ===
const wallet = await WalletBuilder.build(
  "https://testnet-indexer.midnight.network",        // indexer HTTP
  "wss://testnet-indexer.midnight.network/ws",       // indexer WS
  "http://localhost:9944",                            // proof server (your docker)
  "wss://testnet-node-1.midnight.network",           // node
  seedHex,
  getZswapNetworkId(),
  "error"                                             // log level
);

wallet.start(); // important!

// === Create signer and provider ===
const signer = new InMemorySigner(wallet);
const provider = new ZswapNodeSyncProvider(getZswapNetworkId());

// === Compact runtime with local proof server ===
const runtime = new CompactRuntime(provider, signer, {
  ...defaultProofServiceConfiguration,
  serverUrl: "http://localhost:9944", // ← must match your docker container
});

// === Contract instance ===
export const contract = new AseryxModule.Contract(
  runtime,
  deployment.contractAddress
);

// === Your address ===
export const userAddress = wallet
  .address(getZswapNetworkId())
  .toBech32();

console.log("Midnight client ready →", userAddress);